# Requete 0 :  Descriptifs complet des films et des individus qui ont noté ces films par 5
PREFIX movie: <http://www.semanticweb.org/ing-mustang/ontologies/2024/11/Movie.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT 
    (STR(?movieTitle) AS ?MovieTitle)
    (STR(?releaseDate) AS ?ReleaseDate)
    (STR(?imdbUrl) AS ?IMDbUrl)
    (STR(?movieId) AS ?MovieID)
    (GROUP_CONCAT(STR(?genreName); SEPARATOR=", ") AS ?Genres)
    (STR(?userId) AS ?UserID_Note5)
    (STR(?age) AS ?Age)
    (STR(?gender) AS ?Gender)
    (STR(?occupation) AS ?Occupation)
    (STR(?zipcode) AS ?Zipcode)
    (STR(?itemId) AS ?RatingItemID)
WHERE {
  # Attributs du film
  ?movie movie:movieTitle ?movieTitle .
  ?movie movie:releaseDate ?releaseDate .
  ?movie movie:IMDbUrl ?imdbUrl .
  ?movie movie:movieId ?movieId .
  OPTIONAL {
    ?movie movie:hasForKind ?genre .
    ?genre movie:kind ?genreName .
  }
  
  # Optionnel : Attributs des utilisateurs ayant noté à 5
  OPTIONAL {
    ?ratingInstance rdf:type movie:Rating .
    ?ratingInstance movie:hasForMovie ?movie .
    ?ratingInstance movie:hasForUser ?user .
    ?ratingInstance movie:rate ?rating .
    ?ratingInstance movie:itemId ?itemId .
    FILTER (?rating = 5)
    
    ?user movie:userId ?userId .
    ?user movie:age ?age .
    ?user movie:gender ?gender .
    ?user movie:occupation ?occupation .
    ?user movie:zipcode ?zipcode .
  }
}
GROUP BY ?movieTitle ?releaseDate ?imdbUrl ?movieId ?userId ?age ?gender ?occupation ?zipcode ?itemId


Requete 1 : les films notés à 5 avec les users qui les ont notés à 5
PREFIX movie: <http://www.semanticweb.org/ing-mustang/ontologies/2024/11/Movie.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT 
    (STR(?movieTitle) AS ?MovieTitle)
    (STR(?releaseDate) AS ?ReleaseDate)
    (STR(?imdbUrl) AS ?IMDbUrl)
    (STR(?movieId) AS ?MovieID)
    (GROUP_CONCAT(STR(?genreName); SEPARATOR=", ") AS ?Genres)
    (STR(?userId) AS ?UserID)
    (STR(?age) AS ?Age)
    (STR(?gender) AS ?Gender)
    (STR(?occupation) AS ?Occupation)
    (STR(?zipcode) AS ?Zipcode)
WHERE {
  # Instance de notation
  ?ratingInstance rdf:type movie:Rating .
  ?ratingInstance movie:hasForMovie ?movie .
  ?ratingInstance movie:hasForUser ?user .
  ?ratingInstance movie:rate ?rating .
  
  # Attributs du film
  ?movie movie:movieTitle ?movieTitle .
  ?movie movie:releaseDate ?releaseDate .
  ?movie movie:IMDbUrl ?imdbUrl .
  ?movie movie:movieId ?movieId .
  OPTIONAL {
    ?movie movie:hasForKind ?genre .
    ?genre movie:kind ?genreName .
  }
  
  # Attributs de l'utilisateur ayant noté le film à 5
  ?user movie:userId ?userId .
  ?user movie:age ?age .
  ?user movie:gender ?gender .
  ?user movie:occupation ?occupation .
  ?user movie:zipcode ?zipcode .
  FILTER (?rating = 5)
}
GROUP BY ?movieTitle ?releaseDate ?imdbUrl ?movieId ?userId ?age ?gender ?occupation ?zipcode

#Requete 2 : Trouver les films dont la moyenne des notations est égale à 3
PREFIX movie: <http://www.semanticweb.org/ing-mustang/ontologies/2024/11/Movie.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?movieTitle (AVG(?rating) AS ?averageRating)
WHERE {
  ?ratingInstance rdf:type movie:Rating .
  ?ratingInstance movie:hasForMovie ?movie .
  ?ratingInstance movie:rate ?rating .
  ?movie movie:movieTitle ?movieTitle .
}
GROUP BY ?movieTitle
HAVING (AVG(?rating) = 3)
